package com.example.eletronicengineer.db.DisplayDemand

import java.io.Serializable

class RequirementLeaseConstructionTool(
    var id:String,
    var vipId:String,
    var requirementType:String,
    var requirementVariety:String,
    var projectName:String,
    var projectSite:String,
    var projectTime:String,
    var financeTransportationInsurance:String,
    var distribution:String,
    var partnerAttribute:String,
    var hireFareStandard:String,
    var additonalExplain:String,
    var foundTime:String,
    var founder:String,
    var alterTime:String,
    var alterPeople:String,
    var delFlag:String,
    var version:String,
    var requiremenLeaseServeId:String,
    var requirementLeaseLists:List<requirementLeaseProjectList>?,
    var photoPath:String,
    var validTime:String,
    var name:String,
    var phone:String
): Serializable