package com.example.eletronicengineer.distributionFileSave

import java.io.Serializable

class RequirementLeaseFacility(
    var id:String,
    var vipId:String,
    var requirementType:String,
    var requirementVariety:String,
    var projectName:String,
    var projectSite:String,
    var projectTime:String,
    var financeTransportationInsurance:String,
    var distribution:String,
    var partnerAttribute:String,
    var hireFareStandard:String,
    var additonalExplain:String,
    var name:String,
    var phone:String,
    var foundTime:String,
    var founder:String,
    var alterTime:String,
    var alterPeople:String,
    var delFlag:String,
    var version:String,
    var requiremenLeaseServeId:String,
    var requirementLeaseLists:List<requirementTeamProjectList>?,
    var photoPath:String,
    var validTime:String
): Serializable