package com.example.eletronicengineer.db.DisplayDemand

import java.io.Serializable

class RequirementPersonDetail(
    var id:String,
    var vipId:String,
    var requirementType:String,
    var requirementVariety:String,
    var requirementMajor:String,
    var projectName:String,
    var projectSite:String,
    var planTime:String,
    var workerExperience:String,
    var minAgeDemand:String,
    var maxAgeDemand:String,
    var sexDemand:String,
    var roomBoardStandard:String,
    var journeyCarFare:String,
    var journeySalary:String,
    var needPeopleNumber:String,
    var salaryStandard:String,
    var salaryUnit:String,
    var additonalExplain:String,
    var name:String,
    var phone:String,
    var foundTime:String,
    var founder:String,
    var alterTime:String,
    var delFlag:String,
    var version:String,
    var validTime:String
): Serializable