package com.example.eletronicengineer.db.My

import java.io.Serializable


/**
 * @param userName 用户账号
 * */
class UserSubitemEntity (
    var id:Long?,
    var createTime:Long?,
    var creator:String?,
    var lastUpdatePerson:String?,
    var lastUpdateTime:Long?,
    var companyId:String?,
    var creatorId:String?,
    var email:String?,
    var fullName:String?,
    var headerImg:String?,
    var imgPath:String?,
    var imgRealPath:String?,
    var isAdmin:Int?,
    var parentIds:String?,
    var parentid:String?,
    var password:String?,
    var userName:String,
    var companyIds:String?,
    var roleId:String?,
    var telephone:String?,
    var name:String?,
    var workerSex:Boolean?,
    var birthday:Long?,
    var phone:String,
    var identifyCard:String?,
    var identifyCardPathFront:String?,
    var identifyCardPathContrary:String?,
    var vipAddress:String?,
    var isCredential:Int?,
    var busyLeisure:Int?,
    var mianPartType:String?,
    var totalIntegral:Double?,
    var vipLevel:Int?,
    var ifBlacklist:Int?,
    var twoDimensionCode:Int?,
    var headPortrait:String?,
    var nation:String?,
    var marriageState:Int?,
    var politicsVisage:String?,
    var personAccumulationFundNumber:String?,
    var bloodType:Long?,
    var firstWorkTime:Long?,
    var censusType:Boolean?,
    var personSocialSecurityNumber:String?,
    var educationBackground:String?,
    var graduationAcademy:String?,
    var graduationTime:String?,
    var major:String?,
    var bankCardNumber:String?,
    var bankType:String?,
    var recommendResidueQuantity:Int
):Serializable